export {default as Dashboard} from './pages/Dashboard'
export {default as Home} from './pages/Home'
export {default as SignUp} from './pages/SignUp'
export {default as SignIn} from './pages/SignIn'
export {default as PageNotFound} from './pages/PageNotFound'